spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://test-db:5433/commons-auth
    username: db-username
    password: db-password
    hikari:
      connection-test-query: "SELECT 1"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 19080


icu:
  lowcoder:
    spring:
      commons:
        robot-verification:
          default-tester: "USELESS"
          tencent:
            app-id: "wechat-app-id"
            app-secret-key: "the-app-secret-key**"
        sms:
          lingkai:
            url: "http://sms-gateway:8092/sms"

      cloud:
        auth:
          sms:
            enabled: true